server:
  port: 8081
spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

---
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  config:
    env:
      crossOrigin: https://emcove.herokuapp.com
    activate:
      on-profile: prod

---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/emcovedeb
    username: root
    password: rootpass
  config:
    env:
      crossOrigin: http://localhost:3000
    activate:
      on-profile: dev-mari

---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: rootpass
  config:
    env:
      crossOrigin: http://localhost:3000
    activate:
      on-profile: dev-juli

---
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: rootpass
  config:
    env:
      crossOrigin: http://localhost:3000
    activate:
      on-profile: dev-mica
